npcid = npcs.badfather
max_texts = 6
text[0] = "Hey bestie can you watch my son for a little bit?"
text[1] = "@SUMMON_MEATBABY"
text[2] = "I need to go to 5 Below and steal green headbands for st. Patrick's Day."
text[3] = "He likes basketball by the way maybe dunk a hoop with him or something like that."
text[4] = "@MOVE_UP"
text[5] = "Ok see you later I love you bye."
text[6] = "@DUNKMEAT_TITLE"